- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: maven
      state: installed

  - name: create roboshop system user
    ansible.builtin.user:
       name: roboshop
       shell: /sbin/nologin
       system: true
       home: /app

    